image: python:latest

cache:
  paths:
    - ~/.cache/pip/

stages:
    - style

pylint:
  stage: style
  before_script:
    - pip install -r ci/pylint/requirements.txt
    - chmod +x ci/pylint/runner.sh
  script:
    - ./ci/pylint/runner.sh
  artifacts:
    paths:
      - public
  only:
    - develop
    - master
