# Generated by Django 3.1.7 on 2021-03-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='discountBase',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена на товар без скидки.'),
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена на товар.'),
        ),
        migrations.AlterField(
            model_name='price',
            name='vat',
            field=models.IntegerField(blank=True, choices=[(2, '10 %'), (5, '0 %'), (6, 'не облагается'), (7, '20 %')], help_text='Если параметр не указан, используется ставка НДС, установленная в личном кабинете магазина.', null=True, verbose_name='Идентификатор ставки НДС'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=2000, verbose_name='Ссылка на фото'),
        ),
    ]
