# Generated by Django 3.1.6 on 2021-02-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='urls',
            field=models.ForeignKey(help_text='страниц с описанием товара на вашем сайте; фотографий товара в хорошем качестве. Содержит хотя бы один URL', on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='main.url', verbose_name='Список URL'),
        ),
    ]
