# Generated by Django 3.1.7 on 2021-03-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210329_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteeperiod',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.offer'),
        ),
        migrations.AlterField(
            model_name='lifetime',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.offer'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_set', to='main.offer'),
        ),
        migrations.AlterField(
            model_name='processingstate',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processingState_set', to='main.offer'),
        ),
        migrations.AlterField(
            model_name='shelflife',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.offer'),
        ),
        migrations.AlterField(
            model_name='weightdimension',
            name='length',
            field=models.FloatField(blank=True, help_text='Значение с точностью до тысячных, разделитель целой и дробной части — точка. Пример: 65.55', null=True, verbose_name='Длина, см'),
        ),
    ]
