# Generated by Django 3.1.6 on 2021-03-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210228_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_sku', models.CharField(max_length=255, null=True)),
                ('market_sku', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Дата и время последнего обновления цены на товар')),
                ('discount_base', models.FloatField(null=True, verbose_name='Цена на товар без скидки.')),
                ('value', models.FloatField(null=True, verbose_name='Цена на товар.')),
                ('vat', models.IntegerField(null=True, verbose_name='\nИдентификатор ставки НДС, применяемой для товара:\n2 — 10%.\n5 — 0%.\n6 — не облагается НДС.\n7 — 20%.\nЕсли параметр не указан, используется ставка НДС, установленная в личном кабинете магазина.\n')),
                ('offer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.offer', verbose_name='Информация о цене товара')),
            ],
        ),
    ]
