# Generated by Django 3.1.7 on 2021-04-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210404_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingstate',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processingState_set', to='main.offer'),
        ),
        migrations.AlterField(
            model_name='weightdimension',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weightDimensions', to='main.offer'),
        ),
    ]
