# Generated by Django 3.1.7 on 2021-04-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210417_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='base/base.png', upload_to='', verbose_name='аватарка'),
        ),
    ]
