# Generated by Django 3.1.7 on 2021-03-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210329_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customscommoditycode',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customsCommodityCodes', to='main.offer'),
        ),
        migrations.AlterField(
            model_name='guaranteeperiod',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.offer'),
        ),
        migrations.AlterField(
            model_name='lifetime',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.offer'),
        ),
        migrations.AlterField(
            model_name='shelflife',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.offer'),
        ),
    ]
