# Generated by Django 3.1.7 on 2021-04-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210407_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteeperiod',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guaranteePeriod', to='main.offer'),
        ),
        migrations.AlterField(
            model_name='lifetime',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifeTime', to='main.offer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='partnerOrderId',
            field=models.PositiveIntegerField(null=True, verbose_name='Идентификатор заказа партнера'),
        ),
        migrations.AlterField(
            model_name='processingstate',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processingState', to='main.offer'),
        ),
        migrations.AlterField(
            model_name='shelflife',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelfLife', to='main.offer'),
        ),
    ]
