# Generated by Django 3.1.7 on 2021-03-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210310_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='price',
            old_name='discount_base',
            new_name='discountBase',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='market_sku',
            new_name='marketSku',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='shop_sku',
            new_name='shopSku',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.AlterField(
            model_name='price',
            name='offer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='main.offer', verbose_name='Информация о цене товара'),
        ),
        migrations.AlterField(
            model_name='price',
            name='vat',
            field=models.IntegerField(null=True, verbose_name='\n            Идентификатор ставки НДС, применяемой для товара:\n            2 — 10%.\n            5 — 0%.\n            6 — не облагается НДС.\n            7 — 20%.\n            Если параметр не указан, используется ставка НДС, установленная в личном кабинете магазина.\n            '),
        ),
    ]
