# Generated by Django 3.1.7 on 2021-03-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210310_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplyscheduledays',
            old_name='supply_schedule_day',
            new_name='supplyScheduleDay',
        ),
    ]
