# Generated by Django 3.1.7 on 2021-04-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210407_2109'),
        ('main', '0003_auto_20210408_0049'),
    ]

    operations = [
    ]
