# Generated by Django 3.1.7 on 2021-04-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210419_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customscommoditycode',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customsCommodityCodes', to='main.offer'),
        ),
    ]
