# Generated by Django 3.1.7 on 2021-04-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210425_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.CharField(default='', max_length=255, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=255, verbose_name='YM token'),
        ),
    ]
