# Generated by Django 3.1.7 on 2021-03-21 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210313_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='discountBase',
        ),
        migrations.RemoveField(
            model_name='price',
            name='value',
        ),
        migrations.RemoveField(
            model_name='price',
            name='vat',
        ),
        migrations.AlterField(
            model_name='weightdimension',
            name='offer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weightDimensions', to='main.price', verbose_name='Габариты упаковки и вес товара'),
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discountBase', models.FloatField(null=True, verbose_name='Цена на товар без скидки.')),
                ('value', models.FloatField(null=True, verbose_name='Цена на товар.')),
                ('vat', models.IntegerField(null=True, verbose_name='\n               Идентификатор ставки НДС, применяемой для товара:\n               2 — 10%.\n               5 — 0%.\n               6 — не облагается НДС.\n               7 — 20%.\n               Если параметр не указан, используется ставка НДС, установленная в личном кабинете магазина.\n               ')),
                ('offer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priceData', to='main.price', verbose_name='Данные о цене')),
            ],
        ),
    ]
