# Generated by Django 3.1.7 on 2021-04-08 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20210409_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='main.offer'),
        ),
        migrations.AlterField(
            model_name='guaranteeperiod',
            name='timeUnit',
            field=models.CharField(blank=True, choices=[('HOUR', 'Часы'), ('DAY', 'Дни'), ('WEEK', 'Недели'), ('MONTH', 'Месяцы'), ('YEAR', 'Годы')], max_length=5, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='lifetime',
            name='timeUnit',
            field=models.CharField(blank=True, choices=[('HOUR', 'Часы'), ('DAY', 'Дни'), ('WEEK', 'Недели'), ('MONTH', 'Месяцы'), ('YEAR', 'Годы')], max_length=5, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='shelflife',
            name='timeUnit',
            field=models.CharField(blank=True, choices=[('HOUR', 'Часы'), ('DAY', 'Дни'), ('WEEK', 'Недели'), ('MONTH', 'Месяцы'), ('YEAR', 'Годы')], max_length=5, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='supplyscheduledays',
            name='supplyScheduleDay',
            field=models.CharField(choices=[('MONDAY', 'Понедельник'), ('TUESDAY', 'Вторник'), ('WEDNESDAY', 'Среда'), ('THURSDAY', 'Четверг'), ('FRIDAY', 'Пятница'), ('SATURDAY', 'Суббота'), ('SUNDAY', 'Воскресенье')], help_text='Дни недели, когда вы готовы поставлять товары на склад маркетплейса. Заполняйте поле, чтобы получать рекомендации о пополнении товаров на складе.', max_length=9, null=True, verbose_name='Дни поставки'),
        ),
    ]
