# Generated by Django 3.1.7 on 2021-04-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210425_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop_id',
            field=models.CharField(default='', max_length=255, verbose_name='Shop ID'),
        ),
    ]
