# Generated by Django 3.1.7 on 2021-03-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210321_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='marketSku',
        ),
        migrations.RemoveField(
            model_name='price',
            name='shopSku',
        ),
        migrations.RemoveField(
            model_name='price',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='offer',
            name='marketSku',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='updatedAt',
            field=models.DateTimeField(null=True, verbose_name='Дата и время последнего обновления цены на товар'),
        ),
        migrations.AddField(
            model_name='price',
            name='discountBase',
            field=models.FloatField(null=True, verbose_name='Цена на товар без скидки.'),
        ),
        migrations.AddField(
            model_name='price',
            name='value',
            field=models.FloatField(null=True, verbose_name='Цена на товар.'),
        ),
        migrations.AddField(
            model_name='price',
            name='vat',
            field=models.IntegerField(null=True, verbose_name='\n                   Идентификатор ставки НДС, применяемой для товара:\n                   2 — 10%.\n                   5 — 0%.\n                   6 — не облагается НДС.\n                   7 — 20%.\n                   Если параметр не указан, используется ставка НДС, установленная в личном кабинете магазина.\n                   '),
        ),
        migrations.DeleteModel(
            name='PriceData',
        ),
    ]
