# Generated by Django 3.1.7 on 2021-05-04 13:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0008_user_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesuggestion',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='user',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='base/base.png', upload_to=main.models.get_path,
                                    verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shop_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Shop ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='YM token'),
        ),
    ]
