# Generated by Django 3.1.7 on 2021-04-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopSku', models.CharField(max_length=255, null=True, verbose_name='Ваш SKU')),
                ('marketSku', models.PositiveSmallIntegerField(null=True, verbose_name='SKU на Яндексе — идентификатор текущей карточки товара на Маркете')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название товара')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена на товар, выставленная партнером')),
                ('categoryId', models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор категории товара на Маркете')),
                ('categoryName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название категории товара на Маркете')),
            ],
        ),
        migrations.AlterField(
            model_name='guaranteeperiod',
            name='timeUnit',
            field=models.CharField(blank=True, choices=[('HOUR', 'часы'), ('DAY', 'дни'), ('WEEK', 'недели'), ('MONTH', 'месяцы'), ('YEAR', 'годы')], max_length=5, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='lifetime',
            name='timeUnit',
            field=models.CharField(blank=True, choices=[('HOUR', 'часы'), ('DAY', 'дни'), ('WEEK', 'недели'), ('MONTH', 'месяцы'), ('YEAR', 'годы')], max_length=5, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='shelflife',
            name='timeUnit',
            field=models.CharField(blank=True, choices=[('HOUR', 'часы'), ('DAY', 'дни'), ('WEEK', 'недели'), ('MONTH', 'месяцы'), ('YEAR', 'годы')], max_length=5, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='supplyscheduledays',
            name='supplyScheduleDay',
            field=models.CharField(choices=[('MONDAY', 'понедельник'), ('TUESDAY', 'вторник'), ('WEDNESDAY', 'среда'), ('THURSDAY', 'четверг'), ('FRIDAY', 'пятница'), ('SATURDAY', 'суббота'), ('SUNDAY', 'воскресенье')], help_text='Дни недели, когда вы готовы поставлять товары на склад маркетплейса. Заполняйте поле, чтобы получать рекомендации о пополнении товаров на складе.', max_length=9, null=True, verbose_name='Дни поставки'),
        ),
    ]
