# Generated by Django 3.1.7 on 2021-04-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210410_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseWeightDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(blank=True, help_text='Значение с точностью до тысячных, разделитель целой и дробной части — точка. Пример: 65.55', null=True, verbose_name='Длина, см')),
                ('width', models.FloatField(blank=True, help_text='Значение с точностью до тысячных, разделитель целой и дробной части — точка. Пример: 50.7', null=True, verbose_name='Ширина, см')),
                ('height', models.FloatField(blank=True, help_text='Значение с точностью до тысячных, разделитель целой и дробной части — точка. Пример: 20.0', null=True, verbose_name='Высота, см')),
                ('weight', models.FloatField(blank=True, help_text='С учетом упаковки (брутто). Значение с точностью до тысячных, разделитель целой и дробной части — точка. Пример: 1.001', null=True, verbose_name='Вес в упаковке (брутто), кг')),
            ],
        ),
        migrations.CreateModel(
            name='PriceSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('type', models.CharField(blank=True, choices=[('BUYBOX', 'минимальная цена на Маркете. Это самая низкая цена из предложенных партнерами Маркета, и поней товар продается сейчас. Эта цена обновляется в режиме реального времени. Если вы установите цену нижеили равной минимальной, начнет показываться ваше предложение. Если для этого значения в параметре priceуказана цена, которая совпадает с вашей, значит, ваш товар уже показывается на витрине. Если кроме вас этоттовар продают другие продавцы по такой же цене, их предложения также будут отображаться вместе с вашимипо очереди.'), ('DEFAULT_OFFER', 'рекомендованная Маркетом цена, которая привлекает покупателей. Рассчитываетсятолько для популярных на сервисе товаров и обновляется раз в четыре часа.'), ('MIN_PRICE_MARKET', 'минимальная цена на Маркете. Самая низкая цена среди всех предложенийтовара на Маркете. Эта цена обновляется в режиме реального времени и обеспечивает большее количество показовна Маркете, чем минимальная на Маркете и рекомендованная цена.'), ('MAX_DISCOUNT_BASE', 'максимальная цена товара без скидки (старая цена), при которой он можетбыть показан со скидкой. Данная цена рассчитывается автоматически на основе SKU на Яндексе.'), ('MARKET_OUTLIER_PRICE', 'максимальная цена товара, которая обеспечивает показы на Маркете.Если ваша цена выше указанной, товар будет скрыт, так как цена превышает медианную на Маркете на20% или более.')], max_length=21, null=True, verbose_name='Типы цен')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priceSuggestion', to='main.offer')),
            ],
        ),
        migrations.RemoveField(
            model_name='weightdimension',
            name='height',
        ),
        migrations.RemoveField(
            model_name='weightdimension',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weightdimension',
            name='length',
        ),
        migrations.RemoveField(
            model_name='weightdimension',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='weightdimension',
            name='width',
        ),
        migrations.DeleteModel(
            name='ManufacturerCountry',
        ),
        migrations.AddField(
            model_name='weightdimension',
            name='baseweightdimension_ptr',
            field=models.OneToOneField(auto_created=True, default=133, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.baseweightdimension'),
            preserve_default=False,
        ),
    ]
