# Generated by Django 3.1.7 on 2021-04-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210410_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Страна производства товара')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='manufacturerCountries', to='main.offer')),
            ],
        ),
        migrations.RemoveField(
            model_name='weightdimension',
            name='baseweightdimension_ptr',
        ),
        migrations.AddField(
            model_name='weightdimension',
            name='height',
            field=models.FloatField(blank=True, help_text='Значение с точностью до тысячных, разделитель целой и дробной части — точка. Пример: 20.0', null=True, verbose_name='Высота, см'),
        ),
        migrations.AddField(
            model_name='weightdimension',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weightdimension',
            name='length',
            field=models.FloatField(blank=True, help_text='Значение с точностью до тысячных, разделитель целой и дробной части — точка. Пример: 65.55', null=True, verbose_name='Длина, см'),
        ),
        migrations.AddField(
            model_name='weightdimension',
            name='weight',
            field=models.FloatField(blank=True, help_text='С учетом упаковки (брутто). Значение с точностью до тысячных, разделитель целой и дробной части — точка. Пример: 1.001', null=True, verbose_name='Вес в упаковке (брутто), кг'),
        ),
        migrations.AddField(
            model_name='weightdimension',
            name='width',
            field=models.FloatField(blank=True, help_text='Значение с точностью до тысячных, разделитель целой и дробной части — точка. Пример: 50.7', null=True, verbose_name='Ширина, см'),
        ),
        migrations.DeleteModel(
            name='BaseWeightDimension',
        ),
    ]
