# Generated by Django 3.1.7 on 2021-04-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210413_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='currencyId',
            field=models.CharField(choices=[('RUR', 'Российский рубль')], max_length=3, null=True, verbose_name='Валюта, в которой указана цена на товар.'),
        ),
    ]
