# Generated by Django 3.1.7 on 2021-04-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210416_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='type',
            field=models.CharField(choices=[('AGENCY_COMMISSION', 'Прием и перечисление денег от покупателя (агентское вознаграждение)'), ('FULFILLMENT', 'Обработка товара на складе Маркета'), ('STORAGE', 'Хранение товара на складе Маркета в течение суток'), ('SURPLUS', 'Хранение излишков на складе Маркета'), ('WITHDRAW', 'Вывоз товара со склада Маркета'), ('FEE', 'Размещение товара на Маркете')], max_length=17, null=True, verbose_name='Тип остатков товаров на складе'),
        ),
    ]
