# Generated by Django 3.1.7 on 2021-04-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210416_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='main.offer', verbose_name='Информация об остатках товара на складах.'),
        ),
    ]
