# Generated by Django 3.1.7 on 2021-05-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210516_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesuggestion',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priceSuggestion', to='main.offer'),
        ),
        migrations.AlterField(
            model_name='pricesuggestion',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Указана в рублях. Точность — два знака после запятой', max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
