# Generated by Django 3.1.7 on 2021-05-18 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0015_auto_20210517_2059'),
        ('main', '0016_auto_20210518_1505'),
    ]

    operations = [
    ]
