# Generated by Django 3.1.7 on 2021-05-26 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_merge_20210518_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.ForeignKey(help_text='В ходе обработки заказа Маркет может удалить из него единицы товаров —\n                  при проблемах на складе или по инициативе пользователя.\n                  Если из заказа удалены все единицы товара, его не будет в списке items —\n                  только в списке initialItems.\n                  Если в заказе осталась хотя бы одна единица товара, он будет и в списке items\n                  (с уменьшенным количеством единиц count), и в списке initialItems \n                  (с первоначальным количеством единиц initialCount).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order', verbose_name='Список товаров в заказе после возможных изменений'),
        ),
    ]
